src/Entity/Forum.php
<?php

namespace App\Entity;

use App\Entity\Contracts\BackgroundImageInterface as BackgroundImage;
use App\Entity\Contracts\DomainEventsInterface as DomainEvents;
use App\Event\ForumDeleted;
use App\Event\ForumUpdated;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\Selectable;
use Doctrine\ORM\Mapping as ORM;
use Pagerfanta\Doctrine\Collections\CollectionAdapter;
use Pagerfanta\Doctrine\Collections\SelectableAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Contracts\EventDispatcher\Event;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ForumRepository")
 * @ORM\Table(indexes={
 *     @ORM\Index(name="forum_featured_idx", columns={"featured"}),
 *     @ORM\Index(name="forums_light_background_image_id_idx", columns={"light_background_image_id"}),
 *     @ORM\Index(name="forums_dark_background_image_id_idx", columns={"dark_background_image_id"}),
 * }, uniqueConstraints={
 *     @ORM\UniqueConstraint(name="forums_name_idx", columns={"name"}),
 *     @ORM\UniqueConstraint(name="forums_normalized_name_idx", columns={"normalized_name"}),
 * })
 */
class Forum implements BackgroundImage, DomainEvents {
    /**
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Id()
     *
     * @var int|null
     */
    private $id;

    /**
     * @ORM\Column(type="text", unique=true)
     *
     * @var string
     */
    private $name;

    /**
     * @ORM\Column(type="text", unique=true)
     *
     * @var string
     */
    private $normalizedName;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @var string|null
     */
    private $description;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @var string
     */
    private $sidebar;

    /**
     * @ORM\OneToMany(targetEntity="Moderator", mappedBy="forum", cascade={"persist", "remove"})
     *
     * @var Collection<array-key, Moderator>&Selectable<array-key, Moderator>
     */
    private $moderators;

    /**
     * @ORM\OneToMany(targetEntity="Submission", mappedBy="forum", cascade={"remove"}, fetch="EXTRA_LAZY")
     *
     * @var Collection<array-key, Submission>&Selectable<array-key, Submission>
     */
    private $submissions;

    /**
     * @ORM\Column(type="datetimetz_immutable")
     *
     * @var \DateTimeImmutable
     */
    private $created;

    /**
     * @ORM\OneToMany(targetEntity="ForumSubscription", mappedBy="forum",
     *     cascade={"persist", "remove"}, orphanRemoval=true, fetch="EXTRA_LAZY")
     *
     * @var Collection<array-key, ForumSubscription>&Selectable<array-key, ForumSubscription>
     */
    private $subscriptions;

    /**
     * @ORM\OneToMany(targetEntity="ForumBan", mappedBy="forum", cascade={"persist", "remove"})
     *
     * @var Collection<array-key, ForumBan>&Selectable<array-key, ForumBan>
     */
    private $bans;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     *
     * @var bool
     */
    private $featured = false;

    /**
     * @ORM\Column(type="boolean", options={"default": true})
     *
     * @var bool
     */
    private $moderationLogPublic = true;

    /**
     * @ORM\JoinTable(name="forums_tags", joinColumns={
     *     @ORM\JoinColumn(name="forum_id", referencedColumnName="id"),
     * }, inverseJoinColumns={
     *     @ORM\JoinColumn(name="tag_id", referencedColumnName="id"),
     * })
     * @ORM\ManyToMany(targetEntity="ForumTag", inversedBy="forums", cascade={"persist"}, fetch="EXTRA_LAZY")
     *
     * @var Collection<array-key, ForumTag>&Selectable<array-key, ForumTag>
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="Image", cascade={"persist"})
     *
     * @var Image|null
     */
    private $lightBackgroundImage;

    /**
     * @ORM\ManyToOne(targetEntity="Image", cascade={"persist"})
     *
     * @var Image|null
     */
    private $darkBackgroundImage;

    /**
     * @ORM\Column(type="text", options={"default": BackgroundImage::BACKGROUND_TILE})
     *
     * @var string
     */
    private $backgroundImageMode = BackgroundImage::BACKGROUND_TILE;

    /**
     * @ORM\JoinColumn(onDelete="SET NULL")
     * @ORM\ManyToOne(targetEntity="Theme")
     *
     * @var Theme|null
     */
    private $suggestedTheme;

    /**
     * @ORM\OneToMany(targetEntity="ForumLogEntry", mappedBy="forum", cascade={"persist", "remove"})
     * @ORM\OrderBy({"timestamp": "DESC"})
     *
     * @var Collection<array-key, ForumLogEntry>&Selectable<array-key, ForumLogEntry>
     */
    private $logEntries;

    public function __construct(
        string $name,
        string $title,
        string $description,
        string $sidebar,
        User $user = null
    ) {
        $this->setName($name);
        $this->title = $title;
        $this->description = $description;
        $this->sidebar = $sidebar;
        $this->created = new \DateTimeImmutable('@'.time());
        $this->tags = new ArrayCollection();
        $this->bans = new ArrayCollection();
        $this->moderators = new ArrayCollection();
        $this->submissions = new ArrayCollection();
        $this->subscriptions = new ArrayCollection();
        $this->logEntries = new ArrayCollection();

        if ($user) {
            $this->addModerator(new Moderator($this, $user));
            $this->subscribe($user);
        }
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getName(): string {
        return $this->name;
    }

    public function setName(string $name): void {
        $this->name = $name;
        $this->normalizedName = self::normalizeName($name);
    }

    public function getNormalizedName(): ?string {
        return $this->normalizedName;
    }

    public function getTitle(): string {
        return $this->title;
    }

    public function setTitle(string $title): void {
        $this->title = $title;
    }

    public function getDescription(): ?string {
        return $this->description;
    }

    public function setDescription(?string $description): void {
        $this->description = $description;
    }

    public function getSidebar(): string {
        return $this->sidebar;
    }

    public function setSidebar(string $sidebar): void {
        $this->sidebar = $sidebar;
    }

    /**
     * @return array<Moderator>
     */
    public function getModerators(): array {
        return $this->moderators->getValues();
    }

    /**
     * @return Pagerfanta<Moderator>
     */
    public function getPaginatedModerators(int $page, int $maxPerPage = 25): Pagerfanta {
        $criteria = Criteria::create()->orderBy(['timestamp' => 'ASC']);

        $moderators = new Pagerfanta(new SelectableAdapter($this->moderators, $criteria));
        $moderators->setMaxPerPage($maxPerPage);
        $moderators->setCurrentPage($page);

        return $moderators;
    }

    public function userIsModerator($user, bool $adminsAreMods = true): bool {
        if (!$user instanceof User) {
            return false;
        }

        if ($adminsAreMods && $user->isAdmin()) {
            return true;
        }

        // optimised to significantly lessen the number of SQL queries performed
        // when logged in as the user being checked.
        $user->getModeratorTokens()->get(-1);

        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('forum', $this));

        return \count($user->getModeratorTokens()->matching($criteria)) > 0;
    }

    public function addModerator(Moderator $moderator): void {
        if (!$this->moderators->contains($moderator)) {
            $this->moderators->add($moderator);
        }
    }

    public function userCanDelete($user): bool {
        if (!$user instanceof User) {
            return false;
        }

        if ($user->isAdmin()) {
            return true;
        }

        if (!$this->userIsModerator($user)) {
            return false;
        }

        return \count($this->submissions) === 0;
    }

    public function getSubmissionCount(): int {
        return \count($this->submissions);
    }

    public function addSubmission(Submission $submission): void {
        if ($submission->getForum() !== $this) {
            throw new \InvalidArgumentException(
                'Forum does not belong to submission',
            );
        }

        if (!$this->submissions->contains($submission)) {
            $this->submissions->add($submission);
        }
    }

    public function removeSubmission(Submission $submission): void {
        $this->submissions->removeElement($submission);
    }

    public function getCreated(): \DateTimeImmutable {
        return $this->created;
    }

    public function getSubscriptionCount(): int {
        return \count($this->subscriptions);
    }

    public function isSubscribed(User $user): bool {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('user', $user));

        return \count($this->subscriptions->matching($criteria)) > 0;
    }

    public function subscribe(User $user): void {
        if (!$this->isSubscribed($user)) {
            $this->subscriptions->add(new ForumSubscription($user, $this));
        }
    }

    public function unsubscribe(User $user): void {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('user', $user));

        $subscription = $this->subscriptions->matching($criteria)->first();

        if ($subscription) {
            $this->subscriptions->removeElement($subscription);
        }
    }

    public function userIsBanned(User $user): bool {
        if ($user->isAdmin()) {
            // should we check for mod permissions too?
            return false;
        }

        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('user', $user))

src/Form/UserType.php
<?php

namespace App\Form;

use App\DataObject\UserData;
use App\Form\EventListener\PasswordHashingSubscriber;
use App\Form\Type\HoneypotType;
use App\Repository\SiteRepository;
use App\Security\Authentication;
use Gregwar\CaptchaBundle\Type\CaptchaType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

final class UserType extends AbstractType {
    /**
     * @var UserPasswordHasherInterface
     */
    private $hasher;

    /**
     * @var SiteRepository
     */
    private $sites;

    /**
     * @var Authentication
     */
    private $authentication;

    /**
     * @var AuthorizationCheckerInterface
     */
    private $authorizationChecker;

    public function __construct(
        UserPasswordHasherInterface $hasher,
        SiteRepository $sites,
        Authentication $authentication,
        AuthorizationCheckerInterface $authorizationChecker
    ) {
        $this->hasher = $hasher;
        $this->sites = $sites;
        $this->authentication = $authentication;
        $this->authorizationChecker = $authorizationChecker;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void {
        if ($options['honeypot']) {
            $builder->add('phone', HoneypotType::class);
        }

        $editing = $builder->getData() && $builder->getData()->getId();

        $editUsername = true;
        if ($editing) {
            $user = $this->authentication->getUser();
            $editUsername = $this->authorizationChecker->isGranted('edit_username', $user);
        }

        $builder
            ->add('username', TextType::class, [
                'label' => 'label.username',
                'help' => 'user.username_rules',
                'disabled' => !$editUsername,
            ])
            ->add('password', RepeatedType::class, [
                'help' => 'user.password_rules',
                'property_path' => 'plainPassword',
                'required' => !$editing,
                'first_options' => ['label' => $editing ? 'label.new_password' : 'label.password'],
                'second_options' => ['label' => $editing ? 'label.repeat_new_password' : 'label.repeat_password'],
                'type' => PasswordType::class,
            ])
            ->add('email', EmailType::class, [
                'label' => 'label.email_address',
                'help' => 'user.email_optional',
                'required' => false,
            ]);

        if (!$editing && $this->sites->findCurrentSite()->isRegistrationCaptchaEnabled()) {
            $builder->add('verification', CaptchaType::class, [
                'label' => 'label.verification',
                'as_url' => true,
                'reload' => true,
            ]);
        }

        $builder->addEventSubscriber(new PasswordHashingSubscriber($this->hasher));
    }

    public function finishView(FormView $view, FormInterface $form, array $options): void {
        if ($form->getData() && $form->getData()->getId()) {
            // don't auto-complete the password fields when editing the user
            $view['password']['first']->vars['attr']['autocomplete'] = 'new-password';
            $view['password']['second']->vars['attr']['autocomplete'] = 'new-password';
        }
    }

    public function configureOptions(OptionsResolver $resolver): void {
        $resolver->setDefaults([
            'data_class' => UserData::class,
            'honeypot' => true,
            'validation_groups' => static function (FormInterface $form) {
                if ($form->getData()->getId() !== null) {
                    $groups[] = 'edit';
                } else {
                    $groups[] = 'registration';
                }

                return $groups;
            },
        ]);

        $resolver->setAllowedTypes('honeypot', ['bool']);
    }
}

src/Controller/Api/UserController.php
<?php

namespace App\Controller\Api;

use App\Controller\AbstractController;
use App\DataObject\ModeratorData;
use App\DataObject\UserData;
use App\Entity\Submission;
use App\Entity\User;
use App\SubmissionFinder\Criteria;
use App\SubmissionFinder\SubmissionFinder;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @IsGranted("ROLE_USER")
 * @Route("/users", defaults={"_format": "json"}, requirements={"id": "%number_regex%"})
 */
final class UserController extends AbstractController {
    /**
     * @Route("/{id}", methods={"GET"})
     */
    public function read(User $user): Response {
        return $this->json($user, 200, [], [
            'groups' => ['user:read', 'abbreviated_relations'],
        ]);
    }

    /**
     * @Route("/self", methods={"GET"})
     */
    public function self(): Response {
        return $this->json($this->getUser(), 200, [], [
            'groups' => ['abbreviated_relations'],
        ]);
    }

    /**
     * @Route("/{id}/preferences", methods={"GET"})
     * @IsGranted("edit_user", subject="user")
     */
    public function readPreferences(User $user): Response {
        return $this->json($user, 200, [], [
            'groups' => ['user:preferences'],
        ]);
    }

    /**
     * @Route("/{id}/preferences", methods={"PUT"})
     * @IsGranted("edit_user", subject="user")
     */
    public function updatePreferences(User $user, EntityManagerInterface $em): Response {
        return $this->apiUpdate(new UserData($user), UserData::class, [
            'normalization_groups' => ['user:preferences'],
            'denormalization_groups' => ['user:preferences'],
            'validation_groups' => ['settings'],
        ], static function (UserData $data) use ($em, $user): void {
            $data->updateUser($user);

            $em->flush();
        });
    }

    /**
     * @Route("/{id}/submissions", methods={"GET"})
     */
    public function readSubmissions(User $user, SubmissionFinder $finder): Response {
        $criteria = (new Criteria(Submission::SORT_NEW))
            ->showUsers($user);

        return $this->json($finder->find($criteria), 200, [], [
            'groups' => ['submission:read', 'abbreviated_relations'],
        ]);
    }

    /**
     * @Route("/{id}/moderator_of", methods={"GET"})
     */
    public function readModeratedForums(User $user): Response {
        // TODO: pagination
        return $this->json([
            'entries' => $user->getModeratorTokens()->map(static function ($token) {
                return new ModeratorData($token);
            }),
        ], 200, [], [
            'groups' => ['moderator:user-side', 'abbreviated_relations'],
        ]);
    }
}

templates/user/_macros.html.twig
{##
 # - flag (string): one of App\Entity\UserFlags constants
 # - class (string): Additional classes
 #}
{%- macro user_link(user, options) -%}
  <a href="{{ path('user', { username: user.username }) }}" class="{{ options.class ?? '' }}">
    {{- (options.prefix ?? false) ? '/u/' -}}
    {{- user.username -}}
  </a>
  {%- with { flag: _self.user_flag(options.flag ?? constant('App\\Entity\\UserFlags::FLAG_NONE')) } -%}
    {{ (flag ? ' '~flag)|raw }}
  {%- endwith -%}
{%- endmacro user_link -%}

{% macro user_flag(flag) %}
  {%- if flag is constant('App\\Entity\\UserFlags::FLAG_NONE') -%}
  {%- elseif flag is constant('App\\Entity\\UserFlags::FLAG_ADMIN') -%}
    <small class="fg-red text-sm user-flag ">{{ 'user_flag.admin'|trans }}</small>
  {%- elseif flag is constant('App\\Entity\\UserFlags::FLAG_MODERATOR') -%}
    <small class="fg-green text-sm user-flag">{{ 'user_flag.moderator'|trans }}</small>
  {%- else -%}
    <small class="fg-grey text-sm user-flag">{{ flag|trans }}</small>
  {%- endif -%}
{% endmacro user_flag %}

templates/user/_nav.html.twig
<nav class="user-nav">
  <ul class="unlistify flex">
    {% for tab in [
      { path: 'user', label: 'label.overview' },
      { path: 'user_submissions', label: 'user.submissions' },
      { path: 'user_comments', label: 'user.comments' },
    ] %}
      <li>
        <a href="{{ path(tab.path, {username: user.username}) }}"
           class="tab {{ tab.path == current ? 'tab--active' }}">
          {{- tab.label|trans -}}
        </a>
      </li>
    {% endfor %}
  </ul>
</nav>

<h1 class="page-heading break-text no-desktop">{{ user.username }}</h1>

templates/user/base.html.twig
{% extends 'base.html.twig' %}
{% from '_macros/icon.html.twig' import icon %}

{% block site_nav_active app.user is same as(user) ? 'user' %}
{% block user_toolbox_active app.request.attributes.get('_route') %}

{% block sidebar %}
  {% from '_macros/time.html.twig' import relative_time %}

  <section class="sidebar__section flow break-text">
    <header>
      <h1 class="sidebar__title">
        <a href="{{ path('user', {username: user.username}) }}">{{ user.username }}</a>
        {% if user.admin %}
          <span title="{{ 'user_flag.admin'|trans }}">
          {{ icon('wrench', 'user_flag.admin'|trans, '', 'text-sm') }}
        </span>
        {% endif %}
      </h1>

      <p>
        <small class="fg-muted text-sm">{{ 'user.registered'|trans({
            '%timestamp%': relative_time(user.created, { time_format: 'none', natural: true })
          })|raw }}
        </small>

        {% if user is same as(app.user) or is_granted('ROLE_ADMIN') %}
          <br>
          <small class="fg-muted text-sm">
            {%- if user.whitelisted -%}
              {{ 'label.whitelisted'|trans -}}
            {%- else -%}
              {{ 'label.not_whitelisted'|trans -}}
            {%- endif -%}
          </small>
        {% endif %}
      </p>
    </header>

    {% if user.biography is not empty %}
      <div class="user-bio__biography text-flow">{{ user.biography|markdown|raw }}</div>
    {% endif %}

    {% if user is same as(app.user) and is_granted('edit_biography', user) %}
      <p>
        <a href="{{ path('edit_biography', { username: user.username }) }}"
           class="button button--flex button--small button--secondary">
          {{ icon('pencil') }}
          <span>{{ 'nav.edit_biography'|trans }}</span>
        </a>
      </p>
    {% endif %}

    {% if is_granted('ROLE_USER') and app.user.blocking(user) %}
      <form action="{{ path('unblock_user', { username: user.username }) }}" method="POST">
        <input type="hidden" name="token" value="{{ csrf_token('unblock') }}">

        <p>
          <button class="button button--secondary">
            {{- 'action.unblock'|trans -}}
          </button>
        </p>
      </form>
    {% endif  %}
  </section>

  {% set active_ban = user.activeBan %}

  {% if is_granted('ROLE_ADMIN') and active_ban %}
    <section class="sidebar__section flow bg-red">
      <h1 class="sidebar__title">{{ 'heading.this_user_is_banned'|trans }}</h1>

      <dl class="definition-list">
        <dt>{{ 'label.reason'|trans }}</dt>
        <dd>{{ active_ban.reason }}</dd>

        <dt>{{ 'label.banned_by'|trans }}</dt>
        <dd>
          <a href="{{ path('user', { username: active_ban.bannedBy.username }) }}">
            {{- active_ban.bannedBy.username -}}
          </a>
        </dd>

        <dt>{{ 'label.expires'|trans }}</dt>
        <dd>
          {%- if active_ban.expires -%}
            {{ relative_time(active_ban.expires) }}
          {%- else -%}
            <small class="fg-muted text-md">{{ 'label.never'|trans }}</small>
          {%- endif -%}
        </dd>
      </dl>

      <p>
        <a href="{{ path('unban_user', { username: user.username }) }}"
           class="button">
          {{- 'action.unban'|trans -}}
        </a>
      </p>
    </section>
  {% endif %}

  {% set toolbox_items = {
    ('user.message'|trans): {
      route: 'compose_message',
      condition: is_granted('ROLE_USER') and user is not same as(app.user) and is_granted('message', user),
    },
    ('nav.block_user'|trans): {
      route: 'block_user',
      condition: is_granted('ROLE_USER') and user is not same as(app.user) and not app.user.isBlocking(user),
    },
    ('action.ban'|trans): {
      route: 'ban_user',
      condition: is_granted('ROLE_ADMIN') and user is not same as(app.user) and not active_ban,
    },
    ('nav.forum_bans'|trans): {
      route: 'user_forum_bans',
      condition: is_granted('ROLE_ADMIN')
    },
    ('nav.edit_biography'|trans): {
      route: 'edit_biography',
      condition: is_granted('edit_biography', user) and user is not same as(app.user)
    },
    ('nav.hidden_forums'|trans): {
      route: 'hidden_forums',
      condition: is_granted('ROLE_USER') and user is same as(app.user)
    },
    ('nav.trash'|trans): {
      'route': 'user_trash',
      condition: is_granted('ROLE_ADMIN') or user is same as(app.user)
    },
  } %}

  {% set open = false %}
  {% for label in toolbox_items|keys|sort|filter(label => toolbox_items[label].condition) %}
    {% if loop.first %}
      {% set open = true %}
      <section class="sidebar__section flow">
        <h1 class="sidebar__title">{{ 'label.toolbox'|trans }}</h1>
        <ul class="unlistify sidebar__no-padding">
    {% endif %}
    {% set item = toolbox_items[label] %}
    <li>
      <a href="{{ path(item.route, { username: user.username }) }}"
         class="menu-item {{ block('user_toolbox_active') == item.route ? 'menu-item--active' }}">
        {{- label -}}
      </a>
    </li>
  {% endfor %}
  {% if open %}
        </ul>
      </section>
  {% endif %}

  {% if is_granted('ROLE_ADMIN') %}
    <section class="sidebar__section flow">
      <h1 class="sidebar__title">{{ 'heading.whitelisting'|trans }}</h1>

      <p class="fg-muted">{{ 'help.whitelisting'|trans }}</p>

      <form action="{{ path(user.whitelisted ? 'user_dewhitelist' : 'user_whitelist', {username: user.username}) }}" method="post" class="form">
        <input type="hidden" name="token" value="{{ csrf_token('whitelist') }}">
        <div class="form-flex form__row">
          <button class="button button--secondary">
            {{ not user.whitelisted ? 'action.whitelist'|trans : 'action.whitelist_remove'|trans }}
          </button>
        </div>
      </form>
    </section>
  {% endif %}

  {% if user.moderatorTokens|length > 0 %}
    <section class="sidebar__section flow">
      <h1 class="sidebar__title break-text">{{ 'user.moderates'|trans({'%username%': user.username}) }}</h1>

      <ul class="unlistify flex flex--guttered flex--slim-gutters">
        {% for token in user.moderatorTokens %}
          <li>
            <a href="{{ path('forum', {forum_name: token.forum.name}) }}"
               class="button button--secondary button--small">
              {{- token.forum.name -}}
            </a>
          </li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}
{% endblock %}

templates/user/list.html.twig
{% extends 'base.html.twig' %}

{% block site_nav_active 'admin' %}
{% block site_nav_main_menu_active 'users' %}
{% block title 'title.list_of_users'|trans({'%page%': page|format_number}) %}

{% block head %}
  {{ include('_includes/meta_pagination.html.twig', {pager: users}, with_context=false) }}
{% endblock head %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  <details>
    <summary>{{ 'nav.filter_results'|trans }}</summary>

    {{ form_start(form) }}
      {{ form_rest(form) }}

      <div class="form__row">
        <button class="button">{{ 'action.filter'|trans }}</button>
      </div>
    {{ form_end(form) }}
  </details>

  {% embed '_layouts/table.html.twig' with { items: users } %}
    {% block header %}
      <th class="table__shrink">{{ 'label.id'|trans }}</th>
      <th>{{ 'label.username'|trans }}</th>
      <th>{{ 'label.registration_date'|trans }}</th>
      <th>{{ 'label.role'|trans }}</th>
      <th>{{ 'label.moderates'|trans }}</th>
      <th class="table__shrink"><abbr title="{{ 'label.submissions'|trans }}">{{ 'label.submissions_short'|trans }}</abbr></th>
      <th class="table__shrink"><abbr title="{{ 'label.comments'|trans }}">{{ 'label.comments_short'|trans }}</abbr></th>
      <th class="table__shrink"><abbr title="{{ 'label.submission_votes'|trans }}">{{ 'label.submission_votes_short'|trans }}</abbr></th>
      <th class="table__shrink"><abbr title="{{ 'label.comment_votes'|trans }}">{{ 'label.comment_votes_short'|trans }}</abbr></th>
    {% endblock header %}

    {% block row %}
      {% from '_macros/time.html.twig' import relative_time %}
      {% from 'user/_macros.html.twig' import user_link %}
      <td class="table__shrink">{{ item.id }}</td>
      <td>{{ user_link(item) }}</td>
      <td>
        {{ relative_time(item.created, { date_format: 'short', time_format: 'none' }) }}
      </td>
      <td>{{ item.admin ? ('label.admin'|trans) : item.whitelisted ? ('label.whitelisted'|trans) : '-' }}</td>
      <td>
        {% with { count: item.moderatorTokens|length } %}
          {{ count > 0 ? 'label.forums_count'|trans({'%count%': count}) : '-' }}
        {% endwith %}
      </td>
      <td class="table__shrink">
        {% with { count: item.submissionCount } %}
          {{ count > 0 ? count|format_number : '-' }}
        {% endwith %}
      </td>
      <td class="table__shrink">
        {% with { count: item.commentCount } %}
          {{ count > 0 ? count|format_number : '-' }}
        {% endwith %}
      </td>
      <td class="table__shrink">
        {% with { count: item.submissionVoteCount } %}
          {{ count > 0 ? count|format_number : '-' }}
        {% endwith %}
      </td>
      <td class="table__shrink">
        {% with { count: item.commentVoteCount } %}
          {{ count > 0 ? count|format_number : '-' }}
        {% endwith %}
      </td>
    {% endblock row %}
  {% endembed %}
{% endblock body %}